# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: "zh"

pipeline:
  - name: SpacyNLP
    model: "zh_core_web_sm"
  - name: SpacyTokenizer
  - name: sentiment.SentimentAnalyzer
  - name: SpacyEntityExtractor
  - name: RegexFeaturizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat


policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy #处理表单逻辑
