# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: zh

pipeline:
- name: "SpacyNLP"
  model: "zh_core_web_sm"
- name: "SpacyTokenizer"
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "bert-base-chinese"
- name: "DIETClassifier"
  constrain_similarities: True
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100
  retrieval_intent: chitchat
- name: "sentiment"


policies:
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
   - name: RulePolicyPolicies
